name: Update License Year

on:
  schedule:
    - cron: '0 0 1 1 *'  # 每年1月1日运行
  workflow_dispatch:      # 允许手动触发

jobs:
  update-license-year:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Update year in LICENSE
        run: |
          CURRENT_YEAR=$(date +%Y)
          echo "CURRENT_YEAR=$CURRENT_YEAR" >> $GITHUB_ENV
          if [ -f LICENSE ]; then
            sed -i "s/Copyright (c) [0-9]\{4\}/Copyright (c) ${CURRENT_YEAR}/" LICENSE
          fi
          
      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Create Pull Request
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update license year to ${{ env.CURRENT_YEAR }}"
          title: "chore: update license year"
          body: |
            Automated changes:
            - Updated copyright year in LICENSE file to current year
          branch: update-license-year
          base: main
          delete-branch: true
